version: '2'

services:
    application:
        container_name: quick_app
        image: debian
        volumes:
            - ./:/var/www/laravel
    workspace:
        container_name: quick_workspace
        restart: always
        image: sanyok037/qworkspace:v1
        volumes_from:
            - application
        tty: true
    php-fpm:
        container_name: quick_php
        restart: always
        image: sanyok037/qphp:v1
        volumes_from:
            - application
        expose:
            - "9000"
        links:
            - workspace
    nginx:
        container_name: nginx
        restart: always
        image: sanyok037/my_nginx:v2
        volumes_from:
            - data
            - logs
            - application
        ports:
            - "8080:80"
        links:
            - php-fpm
    data:
        container_name: quick_data
        image: debian
        volumes:
            - .docker/mysql:/var/lib/mysql
            - .docker/data:/data
    logs:
        container_name: quick_logs
        image: debian
        volumes:
            - .docker/logs/nginx:/var/log/nginx
            - .docker/logs/mongodb:/var/log/mongodb
    mysql:
        container_name: mysql
        restart: always
        image: mysql
        volumes_from:
            - data
            - logs
        expose:
            - "3306"
        environment:
            MYSQL_DATABASE: homestead
            MYSQL_USER: homestead
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: root
